# Path: /docker-compose.yml

services:
  # Frontend Service (Next.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: barcode-scanner-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PYTHON_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Backend Service (Python Flask)
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: barcode-scanner-backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount model file if it exists locally
      - ./backend/model.pt:/app/model.pt:ro
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: barcode-scanner-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # If you have SSL certificates
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules_cache:
  python_cache:
